config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get '/home/about' => "home#about"
  devise_for :users
  resources :books
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	attachment :profile_image
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { minimum:2}
  validates :name, length: { maximum:20}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

		def after_sign_in_path_for(resource)
			user_path(current_user) 
		end

		def after_sign_out_path_for(resource)
			root_path
		end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_show = Book.find(params[:id]) 
    @user = @book_show.user
    @book = Book.new

  end

  def  create
      @book = Book.new(book_params)      #空のオブジェクトを渡して新規登録から持ってきた情報をbook_paramsに渡している。
      @book.user_id = current_user.id      #誰が投稿したかがわかるようにuser.idが今ログインしているしている人(curret)を指定
      if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created'
    else
      @books = Book.all
      render :index
    end
  end

  def new
  end

  def edit
  @book = Book.find(params[:id])
  end

  def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path, notice: 'Book was successfully destroy'
  end

  def update
  book = Book.find(params[:id])
  book.update(book_params)
  redirect_to book_path(book.id), notice: 'Book was successfully created'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user.id
		@users = User.all
		@book = Book.new
	end

  def show
    @user = User.find(params[:id]) 
    @book = Book.new
    @books = @user.books
  end

  def edit
      @user = User.find(params[:id])
      if current_user.id == @user.id   
      else 
      redirect_to user_path(current_user.id)
      end 
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully update'
    else
      render :edit
    end
  end
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <br>
  <br>
  <%= f.submit "Update Book" %>
<% end %>

<p>
  <%= link_to "show", book_path %>
  |
  <%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-3'>

<% if @book.errors.any? %>
  <div>
    <h3><%= @book.errors.count %>件のerrorが発生しました</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, :fill, 150, 150, format: 'jpeg',fallback: "no-image.png",size:'150x150' %>
<table class="table table-hover">

  <tbody>
    <tr>
      <td>name</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
    <td>introduction</td>
    <td><%= current_user.introduction %></td>
    </tr>
    </tbody>
</table>

<%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<%= render 'layouts/new_book', book: @book %>

</div>

<div class="col-xs-9">
<h1>Books</h1>

	<table class="table table-striped">
		<thead>
			<tr>
				<th><P></P></th>
				<th><P>title</P></th>
				<th><P>opinion</P></th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
      <tr>
				<td>  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg',class: "profile_image", fallback: "no-image.png",size:'60x60' %>  </td>
				<td>  <%= link_to book.title, book_path(book.id) %>  </td>
				<td>  <%= book.body %>  </td>
			</tr>
			<% end %>

		</tbody>
	</table>
</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-3'>

<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpeg',fallback: "no-image.png" ,size:'150x150'%>

<table class="table table-hover">

  <tbody>
    <tr>
      <td>name</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
    <td>introduction</td>
    <td><%= @user.introduction %></td>
    </tr>
    </tbody>

    </table>

      <%= link_to "", edit_user_path(@user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<br>

<%= render 'layouts/new_book', book: @book %>

</div>
<div class="col-xs-9">

<h2>Book detail</h2>

  <table class="table"> 

		<tbody>
      <tr>
				<th><%= attachment_image_tag @book_show.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback:"no-image.png",size:'60x60' %></th>
        <th><%= link_to @user.name, user_path(@user.id)%>
			  <th><%= @book_show.title %></th>
				<th><%= @book_show.body %></th>

      <% if current_user.id == @book_show.user_id %>
        <td><%= link_to "edit", edit_book_path(@book_show.id), class:"btn-sm btn-success" %></td>
				<td><%= link_to "destroy", book_path(@book_show.id), method: :delete, class:"btn-sm btn-danger","data-confirm" =>"本当に消しますか？" %>
        </td>
      <% end %>
			</tr>
		</tbody>
	</table>
  </div>
  </div>

app/views/home/about.html.erb
 <div class="top-text">
 	<h1>
 		Welcome to Bookers!
 	</h1>
 </div>

app/views/home/top.html.erb
        <p id="notice">Signed out successfully.</p>


      	<div class="row">
        <div class='top-message col-md-offset-3 col-md-6'>
          <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

        <div class="btn-wrapper">
        <div class="row">
          <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
        </div>
        <div class="row">
          <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
        </div>
        </div>
            
  </div>
</div>

app/views/layouts/_new_book.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>
  <label>Title</label> 
  <%= f.text_field :title %>

  <label>Opinion</label>
  <%= f.text_area :body %>

<div>
  <%= f.submit 'Create Book' %>
  (｢・ω・)｢ｶﾞｵｰ
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <span class="title_bar">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li> 
                <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>   
              <li>
                <%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %></li>   
              <li>
                <%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %></li>   
              <li>
                <%= link_to " logout", destroy_user_session_path, { method: :delete, data: {confirm: "ログアウトしますか？"}, class: "glyphicon glyphicon-log-out"} %>
              </li>
            <% else %> 
              <li>
                <%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %>
              </li>
              <li>
                <%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class='container'>
      test
      <%= yield %>
    </div>
    <footer>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div>
    <h3><%= @user.errors.count %>件のerrorが発生しました</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1>User info</h1>

<%= form_for(@user) do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.attachment_field :profile_image%>

  <h4>introduction</h4>
  <%= f.text_area :introduction %>

  <%= f.submit 'Update User' %>

<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-3'>

<h2>User info</h2>
	<%= attachment_image_tag current_user, :profile_image, :fill, 150, 150, fallback: "no-image.png",size:'150x150' %>

<table class="table table-hover">

  <tbody>
    <tr>
      <td>name</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
    	<td>introduction</td>
    	<td><%= current_user.introduction %></td>
    </tr>
  </tbody>
</table>
	
<%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<br>

<%= render 'layouts/new_book', book: @book %>

</div>

<div class="col-xs-9">
	<h1>Users</h1>
<table class="table table-striped">
		<thead>
			<tr>
				<th><P>image</P></th>
				<th><P>name</P></th>
				<th><P>show</P></th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>

			<tr class="new-table">
				<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-image.png",size:'60x60' %></td>
				<td><%= user.name %></span></td>
				<td><%= link_to "show",user_path(user) %></td>
			</tr>
			<% end %>

		</tbody>
	</table>
</div>
</div>

app/views/users/karioki.html.erb
  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="nav-top clearfix">
    <div class="slidemenu">
    <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

   <% if user_signed_in? %>

       <li class="">
        <%= link_to 'Home', "/books/new", class: "glyphicon glyphicon-home" %>
       </li>

       <li class="user-matome">
        <%# <%= link_to 'Users', users_path, class: "glyphicon glyphicon-user" %> %>
       </li>

       <li class="">
        <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book" %>
       </li>

       <li class="">
        <a class="glyphicon glyphicon-log-out" "href="></a>
         ::before
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
       </li>

    <% else %>
       <li class="">
        <%= link_to ' Home', "/", class: "glyphicon glyphicon-home" %>
       </li>
       <%# <li class="top-about"> %>
        <%# <%= link_to ' About', about_path ,class: "glyphicon glyphicon-link" %> %>
       </li>
       <li class="">
        <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
       </li>
       <li class="">
        <%= link_to " login", new_user_session_path,class: "glyphicon glyphicon-log-in" %>
       </li>
    <% end %>


    <%= yield %>

  </body>
    </ul>
</div>
	</nav>
</html>


 <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>


   <% if user_signed_in? %>

       <li class="">
        <%= link_to 'Home', "/books/new", class: "glyphicon glyphicon-home" %>
       </li>

       <li class="user-matome">
        <%# <%= link_to 'Users', users_path, class: "glyphicon glyphicon-user" %> %>
       </li>

       <li class="">
        <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book" %>
       </li>

       <li class="">
        <a class="glyphicon glyphicon-log-out" "href="></a>
         ::before
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
       </li>

    <% else %>
       <li class="">
        <%= link_to ' Home', "/", class: "glyphicon glyphicon-home" %>
       </li>
       <%# <li class="top-about"> %>
        <%# <%= link_to ' About', about_path ,class: "glyphicon glyphicon-link" %> %>
       </li>
       <li class="">
        <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
       </li>
       <li class="">
        <%= link_to " login", new_user_session_path,class: "glyphicon glyphicon-log-in" %>
       </li>
    <% end %>


    <%= yield %>

  </body>
    </ul>
</div>
	</nav>
</html>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<div class="container">
  <div class="row">
    <div class='col-xs-3'>

    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'png',fallback: "no-image.png",size:'150x150' %>

      <table class="table table-hover">

        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>


<%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<br>

    <%= render 'layouts/new_book', book: @book %>

</div>

<div class="col-xs-9">
    <h2>Books</h2>
    <table class='table class="table table-striped'>
          <thead>
              <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th cllsapn="4"></th>
              </tr>
          </thead>
		<tbody>
			<% @books.each do |book| %>
      <tr>
				<td>  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "profile_image", fallback: "no-image.png",size:'60x60' %>  </td>
				<td>  <%= link_to book.title, "/books/#{book.id}"%></td>
				<td>  <%= book.body %></td>
			</tr>
			<% end %>

		</tbody>
	</table>
  </div>
  </div>